.public_sensor: &public_sensor
  update_interval: never
  qos: 1
  subscribe_qos: 1

globals:
  - id: soil_probe_version
    type: sensasoil::SoilProbeVersion
    restore_value: yes
    initial_value: "sensasoil::SoilProbeVersion::V3"
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
  # INTERNAL #
  - id: power_sensors_time
    type: unsigned long
    restore_value: no
    initial_value: "0"

sensor:
  - platform: dht
    pin: GPIO5
    model: DHT22
    id: temperature_humidity_sensor
    update_interval: never
    temperature:
      id: ambient_temperature_internal
      internal: true
    humidity:
      id: ambient_humidity_internal
      internal: true
  - platform: adc
    id: battery_voltage_internal
    pin: GPIO3
    attenuation: 12db
    samples: 64
    filters:
    - calibrate_linear:
          - 1.91 -> 3.3
          - 2.40 -> 4.2
    update_interval: never
    internal: true
  - platform: template
    id: battery_level_internal
    lambda: !lambda |-
      const float battery = id(battery_voltage_internal).state;
      if (battery <= 3.3f) {
        return 0.0f;
      }
      if (battery >= 4.2f) {
        return 100.0f;
      }
      return (battery - 3.3f) * (100.0f / (4.2f - 3.3f));
    update_interval: never
    internal: true
  - platform: adc
    id: soil_temperature_v_internal
    attenuation: 12db
    samples: 64
    pin: GPIO1
    update_interval: never
    internal: true
  - platform: adc
    id: soil_volumetric_water_v_internal
    attenuation: 12db
    samples: 64
    pin: GPIO4
    update_interval: never
    internal: true

binary_sensor:
  - platform: gpio
    id: is_battery_charging_internal
    trigger_on_initial_state: true
    use_interrupt: true
    pin:
      number: GPIO6
      mode: 
        input: True
        pullup: True
      inverted: True
    internal: True
  - platform: gpio
    id: factory_reset_internal_button
    trigger_on_initial_state: true
    use_interrupt: True
    pin:
      number: GPIO9
      ignore_strapping_warning: true
      mode:
        input: True
        pullup: True
      inverted: True
    internal: True
    filters:
      - delayed_on: 15s
      - delayed_off: 10ms
    on_press:
      then:
        - button.press: factory_reset_button

output:
  - platform: ledc
    id: led_status_output_internal
    pin: GPIO0

switch:
  - platform: gpio
    id: power_sensors
    pin: GPIO10
    icon: mdi:electric-switch
    name: "Power sensors"
    restore_mode: ALWAYS_OFF
    internal: True
    on_turn_on:
      then:
        - lambda: ! id(power_sensors_time) = millis();

script:
  - id: publish_sensors_specific
    mode: restart
    then:
      # Nothing to publish
      - delay: 1ms

  - id: read_sensors_specific
    mode: restart
    then:
      # Battery charging is automatically updated by the GPIO
      - component.update: battery_voltage_internal
      - component.update: battery_level_internal
      # Update peripherals voltage sensors
      # Turn on peripheral power if not already
      - lambda: |-
          // The if is important to prevent resetting the power_sensors_time
          if (!id(power_sensors).state) {
            id(power_sensors)->turn_on();
          }
      # Wait (hardware dependent delay)
      - delay: !lambda |-
          const unsigned long elapsed = millis() - id(power_sensors_time);
          return elapsed < 80 ? 80 - elapsed : 0;
      - component.update: soil_volumetric_water_v
      - delay: 1ms # yield
      # Wait (hardware dependent delay)
      - delay: !lambda |-
          const unsigned long elapsed = millis() - id(power_sensors_time);
          return elapsed < 100 ? 100 - elapsed : 0;
      - component.update: soil_temperature_v
      - delay: 1ms # yield
      # Wait (hardware dependent delay)
      - delay: !lambda |-
          const unsigned long elapsed = millis() - id(power_sensors_time);
          return elapsed < 150 ? 150 - elapsed : 0;
      - component.update: temperature_humidity_sensor
      - delay: 1ms # yield
      # Turn off peripheral power
      - switch.turn_off: power_sensors
