substitutions:
  MQTT_PREFIX: "ss"
  MQTT_DEFAULT_ADDRESS: "192.168.1.68"
  MQTT_DEFAULT_PORT: "1883"
  # Error timeouts
  DELAY_ERROR_WIFI_MS: "2 * 60 * 1000"
  DELAY_ERROR_MQTT_MS: "2 * 60 * 1000"
  SLEEP_ERROR_WIFI_MS: "5 * 60 * 1000"
  SLEEP_ERROR_MQTT_MS: "5 * 60 * 1000"
  # Constants
  INITIAL_UPDATE_ID: "{0, 0, 0}"
  INITIAL_RECEIVED_UPDATE_ID: "{1, 1, 1}"
  ID_TOPIC: "id"
  ID_PAYLOAD_SIZE: "3" # So it encodes perfectly in 4 Base64URL characters
  ID_PAYLOAD_BASE64_LENGTH: "4"
  STATUS_TOPIC: "s"

globals:
  # CONFIGURABLE BY THE USER #
  - id: mqtt_broker_address
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 254
    initial_value: '"${MQTT_DEFAULT_ADDRESS}"'
  - id: mqtt_broker_port
    type: uint16_t
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    initial_value: ${MQTT_DEFAULT_PORT}
  - id: mqtt_username
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 254
    initial_value: '""'
  - id: mqtt_password
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 254
    initial_value: '""'
  - id: mqtt_discovery_prefix
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 64  # ESPHome's MQTT topic prefix limit
    initial_value: '"homeassistant"'
  - id: wifi_ssid
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 254
    initial_value: '""'
  - id: wifi_password
    type: std::string
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    max_restore_data_length: 254
    initial_value: '""'
  - id: mqtt_tls_flags
    type: uint8_t
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
    initial_value: "0x03" # {RESERVEDx6, VERIFY_SSL, USE_TLS}
  # INTERNAL #
  - id: mqtt_initial_connection_setup
    type: bool
    restore_value: yes
    update_interval: ${SAVE_TO_STORAGE_INTERNAL_INTERVAL}
    initial_value: "true"
  - id: mqtt_data_persisted
    type: bool
    restore_value: no
    initial_value: "false"
  - id: received_update_id
    type: uint8_t[${ID_PAYLOAD_SIZE}]
    restore_value: no
    initial_value: ${INITIAL_RECEIVED_UPDATE_ID}
  - id: current_update_id
    type: uint8_t[${ID_PAYLOAD_SIZE}]
    restore_value: no
    initial_value: ${INITIAL_UPDATE_ID}

mqtt:
  id: mqtt_id
  broker: "127.0.0.1"  # Configured by globals
  username: "u"  # Configured by globals
  password: "p"  # Configured by globals
  idf_send_async: false
  # Let's Encrypt ISRG Root X1 Certificate
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----
  keepalive: 2min  # This value is for manual reset, for sleep cycle it is defined in the mqtt_setup script
  # TODO: Enable when ESPHome supports it
  # clean_session: RTC
  clean_session: True
  enable_on_boot: False
  discover_ip: False
  discovery: False
  on_disconnect:
    # Wait a bit before triggering the disconnect, it might just be a temporary issue
    - delay: 1s
    - lambda: |-
        if (id(mqtt_id)->is_connected()) {
          return;
        }
        id(on_mqtt_disconnect)->execute();
  # This makes Home Assistant always show a status (instead of "unavailable")
  birth_message:
  will_message:
  # No need for shutdown message
  shutdown_message:
  # No need for MQTT logs
  log_topic: null

wifi:
  id: wificomponent
  enable_on_boot: false
  min_auth_mode: WPA
  post_connect_roaming: false
  ssid: "s"  # Configured by globals
  password: "pppppppp"  # Configured by globals
  fast_connect: True
  on_disconnect:
    - script.execute: on_wifi_disconnect

script:
  - id: on_wifi_disconnect
    then:
      - lambda: |-
          // Skip disconnect script if configuring WiFi
          if (id(device_setup_state) == sensasoil::BleSetupState::WIFI_CONFIG) {
            id(on_wifi_disconnect)->stop();
            return;
          }
          ESP_LOGE("on_wifi_disconnect", "WiFi disconnected");
          // Stop main script to avoid conflicts with the disconnect scripts
          id(main_script)->stop();
          // This has priority over MQTT disconnect, so stop it to avoid conflicts
          id(on_mqtt_disconnect)->stop();
          if (id(manual_reset)) {
            // Display led status only if the device is being handled
            // else it would be just uselessly blinking
            auto call = id(led_status)->turn_on();
            call.set_effect("wifi_disconnect_effect");
            call.perform();
          } else {
            // Start error sleep timeout if the error comes after a sleep
            id(send_to_deep_sleep)->execute(${DELAY_ERROR_WIFI_MS}, ${SLEEP_ERROR_WIFI_MS});
          }
          id(last_exec_error) = sensasoil::ErrorCode::WIFI;
      # Wait for WiFi to be connected
      - wait_until:
          wifi.connected
      # No need for timeout in the wait_unit since the send_to_deep_sleep is already handling it
      # Housekeeping
      - lambda: |-
          id(send_to_deep_sleep)->stop();
          auto call = id(led_status)->turn_off();
          call.perform();
          id(main_script)->execute();

  - id: on_mqtt_disconnect
    then:
      - lambda: |-
          // Skip disconnect script if configuring MQTT or on_wifi_disconnect is running
          if (id(device_setup_state) == sensasoil::BleSetupState::MQTT_CONFIG || id(device_setup_state) == sensasoil::BleSetupState::WIFI_CONFIG || id(on_wifi_disconnect)->is_running()) {
            id(on_mqtt_disconnect)->stop();
            return;
          }
          ESP_LOGE("on_mqtt_disconnect", "MQTT disconnected");
          // Stop main script to avoid conflicts with the disconnect scripts
          id(main_script)->stop();
          if (id(manual_reset)) {
            // Display led status only if the device is being handled
            // else it would be just uselessly blinking
            auto call = id(led_status)->turn_on();
            call.set_effect("mqtt_disconnect_effect");
            call.perform();
          } else {
            // Start error sleep timeout if the error comes after a sleep
            id(send_to_deep_sleep)->execute(${DELAY_ERROR_MQTT_MS}, ${SLEEP_ERROR_MQTT_MS});
          }
          id(last_exec_error) = sensasoil::ErrorCode::MQTT;
      # Wait for MQTT to be connected
      - wait_until:
          mqtt.connected
      # No need for timeout in the wait_unit since the send_to_deep_sleep is already handling it
      # Housekeeping
      - lambda: |-
          id(send_to_deep_sleep)->stop();
          auto call = id(led_status)->turn_off();
          call.perform();
          id(main_script)->execute();

  - id: network_setup
    then:
      # TODO: When modem, include modem setup
      - script.execute: wifi_setup
      - script.wait: wifi_setup

  - id: wifi_setup
    then:
      - lambda: |-
          // If no SSID is configured, directly show the WiFi error
          if (id(wifi_ssid) == "") {
            id(on_wifi_disconnect)->execute();
            id(wifi_setup)->stop();
            return;
          }
          // Setup WiFi connection manually based on the stored SSID
          wifi::WiFiAP wifi_wifiap_id = wifi::WiFiAP();
          wifi_wifiap_id.set_ssid(id(wifi_ssid));
          wifi_wifiap_id.set_password(id(wifi_password));
          wifi_wifiap_id.set_priority(0);
          id(wificomponent)->set_sta(wifi_wifiap_id);
          id(wificomponent)->enable();
      - wait_until:
          condition:
            - wifi.connected
          timeout: 30s
      - lambda: |-
          if(id(wificomponent)->is_connected()) {
            return;
          }
          id(on_wifi_disconnect)->execute();

  - id: mqtt_setup
    parameters:
      mqtt_broker_address: std::string
      mqtt_broker_port: uint16_t
      mqtt_username: std::string
      mqtt_password: std::string
      tls_flags: uint8_t
    then:
      # Setup MQTT connection
      - lambda: |-
          // If no broker address is configured, directly show the MQTT error
          if (mqtt_username == "") {
            id(mqtt_setup)->stop();
            id(on_mqtt_disconnect)->execute();
            return;
          }
          static char mac_base64url[sensasoil::MAC_BASE64URL_BUFFER_SIZE];
          sensasoil::get_mac_base64url(mac_base64url);
          char topic_prefix[sizeof("${MQTT_PREFIX}/") + sensasoil::MAC_BASE64URL_LENGTH];
          snprintf(topic_prefix, sizeof(topic_prefix), "${MQTT_PREFIX}/%s", mac_base64url);
          // TODO: Add TLS option when ESPHome supports it, right now it is just always TLS
          id(mqtt_id).set_topic_prefix(topic_prefix, "");
          id(mqtt_id).set_broker_address(mqtt_broker_address);
          id(mqtt_id).set_broker_port(mqtt_broker_port);
          id(mqtt_id).set_username(mqtt_username);
          id(mqtt_id).set_password(mqtt_password);
          id(mqtt_id).set_client_id(mac_base64url);
          if (!id(manual_reset)) {
            // If not a manual reset, set a very short keepalive because we are just sending sensor data <1s
            // The idea is to avoid waiting for the disconnection process, just let the broker handle it
            id(mqtt_id).set_keep_alive(5);
          }
          // These subscriptions are here so there is no need to re-subscribe if the session persisted to save bandwidth
          // Add subscription for last message id
          id(mqtt_id).subscribe(id(mqtt_id).get_topic_prefix() + "/${ID_TOPIC}", [=](const std::string &topic, const std::string &payload) {
                // This is the initial message received after boot, we can use it to check if the data was persisted in the broker
                static const uint8_t initial_update_id[${ID_PAYLOAD_SIZE}] = ${INITIAL_UPDATE_ID};
                if (memcmp(id(current_update_id), initial_update_id, sizeof(id(current_update_id))) == 0) {
                  id(mqtt_data_persisted) = true;
                  return;
                }
                if (payload.length() != ${ID_PAYLOAD_BASE64_LENGTH}) {
                  ESP_LOGW("mqtt_subscription", "Received message with invalid length for update ID: %d, expected: %d", payload.length(), ${ID_PAYLOAD_BASE64_LENGTH});
                  return;
                }
                static uint8_t received_id[${ID_PAYLOAD_SIZE}];
                sensasoil::decode_base64url(payload.c_str(), payload.length(), received_id);
                memcpy(id(received_update_id), received_id, sizeof(id(received_update_id)));
            }, 1);
          id(mqtt_id)->enable();
      - wait_until:
          condition:
            - mqtt.connected
          timeout: 1min # higher timeout since this could be on a NB-IoT connection
      - lambda: |-
          if(id(mqtt_id)->is_connected()) {
            return;
          }
          id(on_mqtt_disconnect)->execute();

  - id: perform_initial_connection
    then:
      - lambda: |-
          // If we are already doing the initial connection, no need to do it again
          if (id(mqtt_initial_connection_setup)) {
            id(perform_initial_connection)->stop();
            return;
          }
      # Wait a bit to make sure the retained message is received
      - wait_until:
          condition:
            - lambda: ! return id(mqtt_data_persisted);
          timeout: 5s
      - lambda: |-
          if (id(mqtt_data_persisted)) {
            id(perform_initial_connection).stop();
            return;
          }
          // If the data is not persisted, we need to do the initial connection setup
          id(mqtt_initial_connection_setup) = true;
          id(mqtt_id)->disable();
      - wait_until:
          condition:
            - not: mqtt.connected
          timeout: 1min
      - script.execute: main_script

  - id: deep_sleep_wait_mqtt
    then:
        # Publish manually the id
        - lambda: |-
            esp_fill_random(id(current_update_id), sizeof(id(current_update_id)));
            const std::string payload_str = sensasoil::encode_base64url(id(current_update_id), sizeof(id(current_update_id)), ${ID_PAYLOAD_BASE64_LENGTH});
            id(publish_mqtt_message)->execute(id(mqtt_id).get_topic_prefix() + "/${ID_TOPIC}", payload_str, 1, true);
        - script.wait: publish_mqtt_message
        # Listen to the final state being published
        - wait_until:
            condition:
              - lambda: ! return memcmp(id(current_update_id), id(received_update_id), sizeof(id(current_update_id))) == 0;
            timeout: 1min
        - lambda: |-
            // Disconnect from MQTT broker will be performed thanks to the short keepalive
            if(memcmp(id(current_update_id), id(received_update_id), sizeof(id(current_update_id))) == 0) {
              // Everything went fine, go to deep sleep
              id(send_to_deep_sleep)->execute(0, id(deep_sleep_duration_internal).state * 60 * 1000);
            } else {
              ESP_LOGE("deep_sleep_wait_mqtt", "MQTT timeout waiting for update ID to be received. current_update_id: %u, received_update_id: %u", id(current_update_id), id(received_update_id));
              id(last_exec_error) = sensasoil::ErrorCode::MQTT_ACK_TIMEOUT;
              // If the message is not received in time, reset with a short deep sleep to avoid blocking the device if something is wrong with the MQTT connection
              id(send_to_deep_sleep)->execute(0, ${SLEEP_ERROR_MQTT_MS});
            }

  - id: publish_mqtt_message
    mode: queued
    parameters:
      topic: std::string
      payload: std::string
      qos: int
      retain: bool
    then:
      # Initial connection check
      - lambda: |-
          if (!id(mqtt_id)->is_connected()) {
            ESP_LOGE("publish_mqtt_message", "Cannot publish MQTT message, not connected to broker");
            id(publish_mqtt_message)->stop();
            return;
          }
      - repeat:
          count: 5
          then:
            - if:
                condition:
                  lambda: |-
                    return id(mqtt_id)->publish(topic, payload, qos, retain);
                then:
                  # Success! Stop the script so we don't retry or hit the error trigger.
                  - script.stop: publish_mqtt_message
                else:
                  # Failed to queue. Wait briefly before trying again.
                  - delay: 500ms
      # Error
      - lambda: |-
          ESP_LOGE("publish_mqtt_message", "Failed to publish MQTT message after multiple attempts. Topic: %s", topic.c_str());
          id(last_exec_error) = sensasoil::ErrorCode::MQTT_PUBLISH_FAILED;
