external_components:
  - source: github://pr#13585
    components: [max17048]
    refresh: 1h
  - source: github://pr#15736
    components: [bq25186]
    refresh: 1h

substitutions:
  ADC_SAMPLES: "5"

globals:
  - id: soil_probe_version
    type: sensasoil::SoilProbeVersion
    restore_value: yes
    initial_value: "sensasoil::SoilProbeVersion::V4"
    update_interval: ${SAVE_TO_STORAGE_USER_CONFIG_INTERVAL}
  # INTERNAL #
  - id: power_sensors_time
    type: unsigned long
    restore_value: no
    initial_value: "0"

sensor:
  - platform: max17048
    id: battery_sensor
    address: 0x36
    update_interval: never
    battery_voltage:
      id: battery_voltage_internal
      internal: true
    battery_level:
      id: battery_level_internal
      internal: true
      filters:
        - lambda: |-
            switch (id(battery_floating_mode)) {
              case sensasoil::BatteryFloatingMode::MAX_CAPACITY:
                return MAX(0.0f, MIN(x, 100.0f));
              case sensasoil::BatteryFloatingMode::MAX_LIFESPAN:
                // In MAX_LIFESPAN mode, the battery level is capped at 50%, interpolate linearly
                return MAX(0.0f, MIN(x * (100.0f / 50.0f), 100.0f));
              case sensasoil::BatteryFloatingMode::BALANCED:
                // In BALANCED mode, the battery level is capped at 80%, interpolate linearly
                return MAX(0.0f, MIN(x * (100.0f / 80.0f), 100.0f));
              default:
                return x;
            }
  - platform: hdc302x
    id: temperature_humidity_sensor
    address: 0x44
    power_mode: ULTRA_LOW_POWER
    update_interval: never
    temperature:
      id: ambient_temperature_internal
      internal: true
    humidity:
      id: ambient_humidity_internal
      internal: true
  - platform: adc
    id: soil_temperature_v_internal
    pin:
      number: GPIO4
      ignore_strapping_warning: true
    attenuation: 12db
    samples: 32
    internal: true
    update_interval: never
    filters:
      - median:
          window_size: ${ADC_SAMPLES}
          send_every: ${ADC_SAMPLES}
          send_first_at: ${ADC_SAMPLES}
  - platform: adc
    id: soil_volumetric_water_v_internal
    pin:
      number: GPIO5
      ignore_strapping_warning: true
    attenuation: 12db
    samples: 32
    internal: true
    update_interval: never
    filters:
      - median:
          window_size: ${ADC_SAMPLES}
          send_every: ${ADC_SAMPLES}
          send_first_at: ${ADC_SAMPLES}

binary_sensor:
  - platform: bq25186
    bq25186_id: bq25186_charger
    charge_done:
      id: is_charging_done_internal
      internal: true
      trigger_on_initial_state: true
      on_state:
        then:
          # Turn off the red LED when charging is done, turn on otherwise
          - lambda: |-
              id(pg_gpo_switch)->control(!x);
    charging:
      id: is_battery_charging_internal
      internal: true
      trigger_on_initial_state: true
  - platform: gpio
    id: factory_reset_internal_button
    use_interrupt: True
    trigger_on_initial_state: true
    pin:
      number: GPIO9
      ignore_strapping_warning: true
      mode:
        input: True
        pullup: True
      inverted: True
    internal: True
    filters:
      - delayed_on: 15s
      - delayed_off: 10ms
    on_press:
      then:
        - button.press: factory_reset_button

output:
  - platform: ledc
    id: led_status_output_internal
    pin:
      number: GPIO15
      ignore_strapping_warning: true

switch:
  - platform: bq25186
    bq25186_id: bq25186_charger
    pg_gpo:
      id: pg_gpo_switch
      internal: true
  - platform: gpio
    id: power_sensors
    pin: GPIO1
    icon: mdi:electric-switch
    name: "Power sensors"
    restore_mode: ALWAYS_OFF
    internal: True
    on_turn_on:
      then:
        - lambda: ! id(power_sensors_time) = millis();

script:
  - id: read_sensors_specific
    mode: restart
    then:
      # Update battery sensor first, since some actions depend on its state
      # and also prevents other stuff from affecting the battery reading (like powering sensors)
      - component.update: battery_sensor
      # Turn on peripheral power if not already
      - lambda: |-
          // The if is important to prevent resetting the power_sensors_time
          if (!id(power_sensors).state) {
            id(power_sensors)->turn_on();
          }
      - delay: 1ms # yield
      # Read some sensors to give some time for the peripherals to stabilize after powering them on
      - component.update: bq25186_charger
      - component.update: temperature_humidity_sensor
      - delay: 1ms # yield
      # Wait (hardware dependent delay)
      - delay: !lambda |-
          const unsigned long elapsed = millis() - id(power_sensors_time);
          return elapsed < 80 ? 80 - elapsed : 0;
      - repeat:
          count: ${ADC_SAMPLES}
          then:
          - component.update: soil_volumetric_water_v_internal
          - delay: 1ms
      # Wait (hardware dependent delay)
      - delay: !lambda |-
          const unsigned long elapsed = millis() - id(power_sensors_time);
          return elapsed < 100 ? 100 - elapsed : 0;
      - repeat:
          count: ${ADC_SAMPLES}
          then:
          - component.update: soil_temperature_v_internal
          - delay: 1ms
      # Turn off peripheral power
      - switch.turn_off: power_sensors
