packages:
  sensasoil_common: !include ../../common/config/common.yaml
  entities: !include entities.yaml

esp32:
  variant: ESP32C6
  framework:
    type: esp-idf

esphome:
  on_boot:
    - priority: -100
      then:
        - if:
            condition:
              lambda: !lambda 'return (id(manual_reset) || id(mqtt_initial_connection_setup));'
            then:
              - bq25186.apply_configuration: bq25186_charger

i2c:
  - id: i2c_bus
    sda: GPIO11
    scl: GPIO10
    frequency: 100kHz
    scan: false
    sda_pullup_enabled: false
    scl_pullup_enabled: false


bq25186:
  id: bq25186_charger
  configure_on_boot: false
  update_interval: never
  fast_charge_current: 400
  watchdog: disabled
  vindpm_mode: battery_tracking
  battery_ocp_limit: 1500ma
  safety_timer: disabled
  input_current_limit: 665ma
  enable_push_button: false
  system_regulation: pass_through
  mask_charge_status_interrupt: true
  mask_vindpm_interrupt: true
  mask_ts_interrupt: true
  mask_treg_interrupt: true
  mask_bat_interrupt: true
  mask_pg_interrupt: true

substitutions:
  HARDWARE_VERSION: "4.0"
  HARDWARE_VERSION_FLAT: "4-0"
  FIRMWARE_VERSION: !env_var FIRMWARE_VERSION
