packages:
  sensasoil_common: !include ../../common/config/common.yaml
  entities: !include entities.yaml

substitutions:
  HARDWARE_VERSION: "4.0"
  HARDWARE_VERSION_FLAT: "4-0"
  FIRMWARE_VERSION: !env_var FIRMWARE_VERSION

esp32:
  variant: ESP32C6
  framework:
    type: esp-idf

esphome:
  on_boot:
    - priority: -100
      then:
        - script.execute:
            id: setup_charger
            force_apply: false

i2c:
  - id: i2c_bus
    sda: GPIO11
    scl: GPIO10
    frequency: 100kHz
    scan: false
    sda_pullup_enabled: false
    scl_pullup_enabled: false


bq25186:
  id: bq25186_charger
  configure_on_boot: false
  update_interval: never
  fast_charge_current: 400
  battery_regulation_voltage: 4000  # By default, reduce strain on the battery by floating it at 4.0V instead of 4.2V
  watchdog: disabled
  vindpm_mode: battery_tracking
  battery_ocp_limit: 1500ma
  safety_timer: disabled
  input_current_limit: 665ma
  enable_push_button: false
  system_regulation: pass_through
  mask_charge_status_interrupt: true
  mask_vindpm_interrupt: true
  mask_ts_interrupt: true
  mask_treg_interrupt: true
  mask_bat_interrupt: true
  mask_pg_interrupt: true

script:
  - id: setup_charger
    mode: restart
    parameters:
      force_apply: bool
    then:
      - lambda: |-
          // Do not apply the configuration unless manual_reset, initial connection or force is true
          if (!(id(manual_reset) || id(mqtt_initial_connection_setup) || force_apply)) {
            id(setup_charger)->stop();
            return;
          }
      - if:
          condition:
            lambda: 'return id(battery_floating_mode) == sensasoil::BatteryFloatingMode::MAX_LIFESPAN;'
          then:
            - bq25186.apply_configuration: 
                id: bq25186_charger
                battery_regulation_voltage: 3800
            - script.stop: setup_charger
      - if:
          condition:
            lambda: 'return id(battery_floating_mode) == sensasoil::BatteryFloatingMode::BALANCED;'
          then:
            - bq25186.apply_configuration: 
                id: bq25186_charger
                battery_regulation_voltage: 4000
            - script.stop: setup_charger
      - if:
          condition:
            lambda: 'return id(battery_floating_mode) == sensasoil::BatteryFloatingMode::MAX_CAPACITY;'
          then:
            - bq25186.apply_configuration: 
                id: bq25186_charger
                battery_regulation_voltage: 4200
            - script.stop: setup_charger
